# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 601)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_1.setGeometry(QtCore.QRect(160, 130, 300, 60))
        self.Btn_1.setStyleSheet("background-color: rgb(255, 144, 146);")
        self.Btn_1.setObjectName("Btn_1")
        self.Btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_2.setGeometry(QtCore.QRect(160, 230, 300, 60))
        self.Btn_2.setStyleSheet("background-color: rgb(255, 252, 157);")
        self.Btn_2.setObjectName("Btn_2")
        self.Btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_3.setGeometry(QtCore.QRect(160, 330, 300, 60))
        self.Btn_3.setStyleSheet("background-color: rgb(160, 255, 149);")
        self.Btn_3.setObjectName("Btn_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_1.setText(_translate("MainWindow", "LED 1"))
        self.Btn_2.setText(_translate("MainWindow", "LED 2"))
        self.Btn_3.setText(_translate("MainWindow", "LED 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
