# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\emoji.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyperclip


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 20, 300, 80))
        self.textEdit.setStyleSheet("font: 14pt \"Arial\";")
        self.textEdit.setObjectName("textEdit")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(10, 160, 150, 150))
        self.btn_1.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_1.setText("")
        self.btn_1.clicked.connect(lambda: pyperclip.copy(self.btn_1.text()))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(170, 160, 150, 150))
        self.btn_2.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_2.setText("")
        self.btn_2.clicked.connect(lambda: pyperclip.copy(self.btn_2.text()))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(330, 160, 150, 150))
        self.btn_3.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_3.setText("")
        self.btn_3.clicked.connect(lambda: pyperclip.copy(self.btn_3.text()))
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(490, 160, 150, 150))
        self.btn_4.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_4.setText("")
        self.btn_4.clicked.connect(lambda: pyperclip.copy(self.btn_4.text()))
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(650, 160, 150, 150))
        self.btn_5.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_5.setText("")
        self.btn_5.clicked.connect(lambda: pyperclip.copy(self.btn_5.text()))
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(10, 330, 150, 150))
        self.btn_6.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_6.setText("")
        self.btn_6.clicked.connect(lambda: pyperclip.copy(self.btn_6.text()))
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(170, 330, 150, 150))
        self.btn_7.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_7.setText("")
        self.btn_7.clicked.connect(lambda: pyperclip.copy(self.btn_7.text()))
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(330, 330, 150, 150))
        self.btn_8.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_8.setText("")
        self.btn_8.clicked.connect(lambda: pyperclip.copy(self.btn_8.text()))
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(490, 330, 150, 150))
        self.btn_9.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_9.setText("")
        self.btn_9.clicked.connect(lambda: pyperclip.copy(self.btn_9.text()))
        self.btn_9.setObjectName("btn_9")
        self.btn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_10.setGeometry(QtCore.QRect(650, 330, 150, 150))
        self.btn_10.setStyleSheet("font: 30pt \"Arial\";")
        self.btn_10.setText("")
        self.btn_10.clicked.connect(lambda: pyperclip.copy(self.btn_10.text()))
        self.btn_10.setObjectName("btn_10")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 130, 770, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
