# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ball_ir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.value_sw = QtWidgets.QLabel(self.centralwidget)
        self.value_sw.setGeometry(QtCore.QRect(270, 100, 100, 40))
        self.value_sw.setStyleSheet("font: 12pt \"Arial\";")
        self.value_sw.setObjectName("value_sw")
        self.label_sw = QtWidgets.QLabel(self.centralwidget)
        self.label_sw.setGeometry(QtCore.QRect(120, 100, 120, 40))
        self.label_sw.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(170, 196, 255);\n"
"border-radius: 5px;")
        self.label_sw.setObjectName("label_sw")
        self.value_ir = QtWidgets.QLabel(self.centralwidget)
        self.value_ir.setGeometry(QtCore.QRect(270, 180, 100, 40))
        self.value_ir.setStyleSheet("font: 12pt \"Arial\";")
        self.value_ir.setObjectName("value_ir")
        self.label_ir = QtWidgets.QLabel(self.centralwidget)
        self.label_ir.setGeometry(QtCore.QRect(120, 180, 120, 40))
        self.label_ir.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 164, 164);\n"
"border-radius: 5px;")
        self.label_ir.setObjectName("label_ir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 350, 80, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.value_sw.setText(_translate("MainWindow", "0"))
        self.label_sw.setText(_translate("MainWindow", "Ball switch"))
        self.value_ir.setText(_translate("MainWindow", "0"))
        self.label_ir.setText(_translate("MainWindow", "IR"))
        self.label.setText(_translate("MainWindow", "made. nh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
