# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\draw.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(160, 90, 150, 60))
        self.label_temp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label_temp.setText("")
        self.label_temp.setObjectName("label_temp")
        self.label_gas = QtWidgets.QLabel(self.centralwidget)
        self.label_gas.setGeometry(QtCore.QRect(360, 90, 150, 60))
        self.label_gas.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label_gas.setText("")
        self.label_gas.setObjectName("label_gas")
        self.label_fire = QtWidgets.QLabel(self.centralwidget)
        self.label_fire.setGeometry(QtCore.QRect(560, 90, 150, 60))
        self.label_fire.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label_fire.setText("")
        self.label_fire.setObjectName("label_fire")
        self.label_now_back = QtWidgets.QLabel(self.centralwidget)
        self.label_now_back.setGeometry(QtCore.QRect(139, 30, 621, 130))
        self.label_now_back.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(170, 164, 255);")
        self.label_now_back.setText("")
        self.label_now_back.setObjectName("label_now_back")
        self.label_now = QtWidgets.QLabel(self.centralwidget)
        self.label_now.setGeometry(QtCore.QRect(50, 30, 101, 131))
        self.label_now.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: rgb(221, 242, 255);")
        self.label_now.setObjectName("label_now")
        self.pushButton_fan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fan.setGeometry(QtCore.QRect(500, 220, 150, 60))
        self.pushButton_fan.setStyleSheet("font: 14pt \"Arial\";")
        self.pushButton_fan.setObjectName("pushButton_fan")
        self.pushButton_servo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_servo.setGeometry(QtCore.QRect(500, 310, 150, 60))
        self.pushButton_servo.setStyleSheet("\n"
"font: 14pt \"Arial\";")
        self.pushButton_servo.setObjectName("pushButton_servo")
        self.pushButton_relay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_relay.setGeometry(QtCore.QRect(500, 400, 150, 60))
        self.pushButton_relay.setStyleSheet("\n"
"font: 14pt \"Arial\";")
        self.pushButton_relay.setObjectName("pushButton_relay")
        self.label_set_back = QtWidgets.QLabel(self.centralwidget)
        self.label_set_back.setGeometry(QtCore.QRect(130, 199, 610, 281))
        self.label_set_back.setStyleSheet("background-color: rgb(170, 164, 255);")
        self.label_set_back.setText("")
        self.label_set_back.setObjectName("label_set_back")
        self.label_set = QtWidgets.QLabel(self.centralwidget)
        self.label_set.setGeometry(QtCore.QRect(30, 200, 111, 281))
        self.label_set.setStyleSheet("border-radius: 15px;\n"
"font: 75 13pt \"Arial\";\n"
"background-color: rgb(221, 242, 255);")
        self.label_set.setObjectName("label_set")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(160, 50, 100, 25))
        self.temp.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(170, 164, 255);")
        self.temp.setObjectName("temp")
        self.gas = QtWidgets.QLabel(self.centralwidget)
        self.gas.setGeometry(QtCore.QRect(360, 50, 100, 25))
        self.gas.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(170, 164, 255);")
        self.gas.setObjectName("gas")
        self.fire = QtWidgets.QLabel(self.centralwidget)
        self.fire.setGeometry(QtCore.QRect(560, 50, 100, 25))
        self.fire.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(170, 164, 255);")
        self.fire.setObjectName("fire")
        self.label_made = QtWidgets.QLabel(self.centralwidget)
        self.label_made.setGeometry(QtCore.QRect(690, 550, 100, 20))
        self.label_made.setObjectName("label_made")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(170, 240, 221, 201))
        self.groupBox.setStyleSheet("background-color: rgb(170, 164, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_auto = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_auto.setGeometry(QtCore.QRect(20, 20, 130, 60))
        self.radioButton_auto.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.radioButton_auto.setObjectName("radioButton_auto")
        self.radioButton_manual = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_manual.setGeometry(QtCore.QRect(20, 120, 130, 60))
        self.radioButton_manual.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.label_fire_detection = QtWidgets.QLabel(self.centralwidget)
        self.label_fire_detection.setGeometry(QtCore.QRect(200, 500, 400, 50))
        self.label_fire_detection.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label_fire_detection.setText("")
        self.label_fire_detection.setObjectName("label_fire_detection")
        self.label_set.raise_()
        self.label_set_back.raise_()
        self.label_now_back.raise_()
        self.label_gas.raise_()
        self.label_fire.raise_()
        self.label_temp.raise_()
        self.label_now.raise_()
        self.pushButton_fan.raise_()
        self.pushButton_servo.raise_()
        self.pushButton_relay.raise_()
        self.temp.raise_()
        self.gas.raise_()
        self.fire.raise_()
        self.label_made.raise_()
        self.groupBox.raise_()
        self.label_fire_detection.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_now.setText(_translate("MainWindow", "Sensing"))
        self.pushButton_fan.setText(_translate("MainWindow", "Fan"))
        self.pushButton_servo.setText(_translate("MainWindow", "Servo"))
        self.pushButton_relay.setText(_translate("MainWindow", "Relay"))
        self.label_set.setText(_translate("MainWindow", "Setting"))
        self.temp.setText(_translate("MainWindow", "Temperature"))
        self.gas.setText(_translate("MainWindow", "Gas"))
        self.fire.setText(_translate("MainWindow", "Fire"))
        self.label_made.setText(_translate("MainWindow", "made. nanhee"))
        self.radioButton_auto.setText(_translate("MainWindow", "Auto"))
        self.radioButton_manual.setText(_translate("MainWindow", "Manual"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
