# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizon_R = QtWidgets.QSlider(self.centralwidget)
        self.horizon_R.setGeometry(QtCore.QRect(180, 80, 160, 30))
        self.horizon_R.setOrientation(QtCore.Qt.Horizontal)
        self.horizon_R.setObjectName("horizon_R")
        self.horizon_B = QtWidgets.QSlider(self.centralwidget)
        self.horizon_B.setGeometry(QtCore.QRect(180, 150, 160, 30))
        self.horizon_B.setOrientation(QtCore.Qt.Horizontal)
        self.horizon_B.setObjectName("horizon_B")
        self.horizon_G = QtWidgets.QSlider(self.centralwidget)
        self.horizon_G.setGeometry(QtCore.QRect(180, 230, 160, 30))
        self.horizon_G.setOrientation(QtCore.Qt.Horizontal)
        self.horizon_G.setObjectName("horizon_G")
        self.label_R = QtWidgets.QLabel(self.centralwidget)
        self.label_R.setGeometry(QtCore.QRect(60, 80, 60, 30))
        self.label_R.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 0, 0);\n"
"")
        self.label_R.setObjectName("label_R")
        self.label_B = QtWidgets.QLabel(self.centralwidget)
        self.label_B.setGeometry(QtCore.QRect(60, 150, 60, 30))
        self.label_B.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255);")
        self.label_B.setObjectName("label_B")
        self.label_G = QtWidgets.QLabel(self.centralwidget)
        self.label_G.setGeometry(QtCore.QRect(60, 230, 60, 30))
        self.label_G.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(0, 255, 0);")
        self.label_G.setObjectName("label_G")
        self.btn_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(120, 320, 150, 90))
        self.btn_color.setObjectName("btn_color")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_R.setText(_translate("MainWindow", "R"))
        self.label_B.setText(_translate("MainWindow", "B"))
        self.label_G.setText(_translate("MainWindow", "G"))
        self.btn_color.setText(_translate("MainWindow", "Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
