# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TH.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        MainWindow.setStyleSheet("background-color: rgb(229, 233, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_humi_value = QtWidgets.QLabel(self.centralwidget)
        self.label_humi_value.setGeometry(QtCore.QRect(125, 150, 100, 30))
        self.label_humi_value.setObjectName("label_humi_value")
        self.label_temp_value = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_value.setGeometry(QtCore.QRect(350, 150, 100, 30))
        self.label_temp_value.setObjectName("label_temp_value")
        self.label_humi = QtWidgets.QLabel(self.centralwidget)
        self.label_humi.setGeometry(QtCore.QRect(75, 90, 150, 30))
        self.label_humi.setStyleSheet("font: 12pt \"Arial\";")
        self.label_humi.setObjectName("label_humi")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(300, 90, 150, 30))
        self.label_temp.setStyleSheet("font: 12pt \"Arial\";")
        self.label_temp.setObjectName("label_temp")
        self.tool = QtWidgets.QLabel(self.centralwidget)
        self.tool.setGeometry(QtCore.QRect(25, 25, 450, 250))
        self.tool.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px")
        self.tool.setText("")
        self.tool.setObjectName("tool")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(375, 280, 100, 20))
        self.label.setObjectName("label")
        self.tool.raise_()
        self.label_humi_value.raise_()
        self.label_temp_value.raise_()
        self.label_humi.raise_()
        self.label_temp.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_humi_value.setText(_translate("MainWindow", "TextLabel"))
        self.label_temp_value.setText(_translate("MainWindow", "TextLabel"))
        self.label_humi.setText(_translate("MainWindow", "Humidity"))
        self.label_temp.setText(_translate("MainWindow", "Temperature"))
        self.label.setText(_translate("MainWindow", "made. nanhee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
