# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RGB LED control.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 360, 100, 40))
        self.pushButton.setStyleSheet("font: 75 12pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 50, 400, 40))
        self.label.setStyleSheet("font: 75 15pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_r = QtWidgets.QLabel(self.centralwidget)
        self.label_r.setGeometry(QtCore.QRect(40, 170, 150, 23))
        self.label_r.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(255, 150, 150);")
        self.label_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r.setObjectName("label_r")
        self.label_g = QtWidgets.QLabel(self.centralwidget)
        self.label_g.setGeometry(QtCore.QRect(230, 170, 150, 23))
        self.label_g.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(150, 255, 150);")
        self.label_g.setAlignment(QtCore.Qt.AlignCenter)
        self.label_g.setObjectName("label_g")
        self.label_b = QtWidgets.QLabel(self.centralwidget)
        self.label_b.setGeometry(QtCore.QRect(420, 170, 150, 23))
        self.label_b.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(150, 150, 255);")
        self.label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b.setObjectName("label_b")
        self.textEdit_g = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_g.setGeometry(QtCore.QRect(240, 210, 130, 50))
        self.textEdit_g.setObjectName("textEdit_g")
        self.textEdit_b = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_b.setGeometry(QtCore.QRect(430, 210, 130, 50))
        self.textEdit_b.setObjectName("textEdit_b")
        self.textEdit_r = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_r.setGeometry(QtCore.QRect(50, 210, 130, 50))
        self.textEdit_r.setObjectName("textEdit_r")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "SEND"))
        self.label.setText(_translate("MainWindow", "RGB LED Control Program"))
        self.label_r.setText(_translate("MainWindow", "RED"))
        self.label_g.setText(_translate("MainWindow", "GREEN"))
        self.label_b.setText(_translate("MainWindow", "BLUE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
